version: '3.8'

services:
  # Service Node.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=user_db
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/src/app/src
    command: npm run dev # Assurez-vous que vous avez un script "dev" dans package.json (pour démarrer en mode développement)

  # Service PostgreSQL
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
